server:
    port: 8081

##APP SPECIFIC CUSTOM PROPERTIES
#app:
#    kafka:
#        producer:
#            topic: <TEST_TOPIC>

##SPRING PROPERTIES
#spring:
#    kafka:
#        bootstrap-servers: localhost:9200,localhost:9300,localhost:9400
#            properties:
#                #Server host name verification is disabled by setting ssl.endpoint.identification.algorithm to an empty string
#                ssl.endpoint.identification.algorithm:
#            producer:
#                retries: 0
#                acks: all
#                key-serializer: org.apache.kafka.common.serialization.StringSerializer
#                value-serializer: org.apache.kafka.common.serialization.StringSerializer



